### ISSUE TITLE
The DeadlineExceeded Exception threw when service is running

### ISSUE THREAD

**Issue by walt-liuzw** [zeebe-io/zeebe-client-csharp#100]
**Describe the bug**
I call ZeebeClient in the microservice to implement the file upload and deployment function. When the service is running normally, I call this API interface to upload the file, and a DeadlineExceeded exception occurs.
`2020-02-21 15:01:01.8615 ERROR Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")`

**To Reproduce**
1. Deploy the running api service, the code:
` var client = ZeebeClient.Builder().UseGatewayAddress(request.ServerUrl).UsePlainText().Build();
                        var deployResponse = await client.NewDeployCommand()
                        .AddResourceString(contentStr, Encoding.UTF8, 
                       fileName).Send(TimeSpan.FromSeconds(30));
                        workflow = deployResponse.Workflows[0];`
2. It can be run immediately after deployment without error, but after a period of time (after 2 hours), it will report an error after executing this API.
3. See error：
`2020-02-21 15:01:01.8615 ERROR Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")
`
**Expected behavior**
I hope that no error will be reported at any time.

**Enviroment (please complete the following information):**
 - OS: aliyun k8s

**Comment by Zelldon** [comment]
Hey @walt-liuzw 

thanks for reporting this. I thin this issue is more an Zeebe Broker or gateway issue. Could you please check the gateway/broker logs. Do you see there any exceptions/logs?

**Comment by walt-liuzw** [comment]
@Zelldon thanks for reply.
i don`t think this issue of broker or gateway. Because when i restart the Microservice it works successfully.
Next I look at the logs. I think that since the DeadlineExceeded Exception is thrown, the Zeebe server should have triggered this exception.

**Comment by Zelldon** [comment]
> i don`t think this issue of broker or gateway. Because when i restart the Microservice it works successfully.

The microservice only contain the client? Do you see before that exceptions any errors in the broker or an restart of a node?

**Comment by Zelldon** [comment]
Feel free to reopen if you have further information.
