### ISSUE TITLE
Topology request should return broker versions

### ISSUE THREAD

**Issue by sergeylebed** [zeebe-io/zeebe-client-csharp#112]
**Is your feature request related to a problem? Please describe.**
It is not possible to get Zeebe version, that is introduced in v0.23, via the current client.

**Describe the solution you'd like**
Adding the Version property to the  topology or broker info.
It should not throw exception if connected to Zeebe prior v0.23.

**Comment by Zelldon** [comment]
Related java feature https://github.com/zeebe-io/zeebe/issues/3692
