### ISSUE TITLE
Implement list workflows and get workflow in csharp client

### ISSUE THREAD

**Issue by jsolana** [zeebe-io/zeebe-client-csharp#134]
Hi, I am newbie with Zeebe and I don't know if is possible to fetch deployed workflows in csharp client as go client (https://github.com/zeebe-io/zeebe/issues/1483). 
I am looking for the same features:

- List workflows
- Get workflow resource

Thanks,

**Comment by Zelldon** [comment]
As you can read in the referenced issue this was also removed on the other clients. This is no longer supported by the broker
