### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-client-csharp#19]
What do you think about renaming the repository to `zeebe-client-csharp` then we could have the naming scheme `zeebe-client-LANGUAGE` for all the clients.

**Comment by Zelldon** [comment]
Hey @menski ,

yes agree that consistent naming would be better, but somehow for me it sounds better if the langauge is before the client (zeebe-*-client) :sweat_smile: :see_no_evil: But might be something which has to get used to.

**Comment by Zelldon** [comment]
done
