### ISSUE TITLE
NewThrowErrorCommand Missing from Client Interface 

### ISSUE THREAD

**Issue by Lamby123** [zeebe-io/zeebe-client-csharp#202]
The  NewThrowErrorCommand is present in the client but is not implemented in the IZeebeClient interface. 

public IThrowErrorCommandStep1 NewThrowErrorCommand(long jobKey)
        {
            return new ThrowErrorCommand(gatewayClient, jobKey);
        }

We would like to use this method but cannot at the moment.

**Comment by Zelldon** [comment]
It is available at the IJobClient https://github.com/zeebe-io/zeebe-client-csharp/blob/master/Client/Api/Worker/IJobClient.cs#L117

**Comment by Lamby123** [comment]
Thanks for the quick response. I will revert back to our developers.
