### ISSUE TITLE
IFinalCommandStep methods should handle a CancellationToken

### ISSUE THREAD

**Issue by xlegalles** [zeebe-io/zeebe-client-csharp#215]
It is a common practice with .NET async methods to pass a `CancellationToken`: timeouts, for instance, are usually handled this way.

The `IFinalCommandStep `methods i.e. `Send `and `SendWithRetry `should pass such a `CancellationToken`: it could be done as alternative signatures (i.e. additional methods) but existing methods would use themselves a cancellation token to manage the timeout.
At the end of the stack, the gRPC API exposes itself such a `CancellationToken`. 

I can do the PR if you agree

**Comment by Zelldon** [comment]
@xlegalles thanks for raising this sounds reasonable to me :+1:
