### ISSUE TITLE
I can use the client to get workflow state/outcome

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-client-csharp#34]
**Is your feature request related to a problem? Please describe.**
A often requested feature is to request the outcome of an workflow.
In the near feature I'm not sure if we want to implement this in the broker, but what we can easily do is to use the hazelcast exporter. The user needs to register the exporter in the broker and the client can connect to the exporter.

In that way the user can request/search for the outcome of an specific workflow instance.

**Describe the solution you'd like**

Either an new API to find/wait for some specific events
OR just a method on the Workflow object to get the result.

```
WorkflowInstance instance = client.Find().WorkflowInstance().WithKey(key);
```

```
WorkflowInstance instance = await client.NewCreateWorkflowInstanceCommand()....Send();
WorkflowInstanceResult result = await instance.Result;
```

It might be better to have the first approach, since then we can check the current state of the workflow instance to see if there is an incident for example or just get the variables.

**Describe alternatives you've considered**
There are none.

**Comment by berndruecker** [comment]
Just curious: Why not wait for the broker to have that feature implemented? Is there a trigger that we need that now in C#?

**Comment by Zelldon** [comment]
No trigger just my wish to build that, since we have the hazelcast connector and I wanted to update him, but then I thought I can just merge them together.

Idk when we will build this in the broker

**Comment by Zelldon** [comment]
see zeebe-io/zeebe#3197

**Comment by mike7ang1rdz** [comment]
Hi.

 I'm currently working on a  similar model implemented in 
https://zeebe.io/blog/2019/08/zeebe-rest-affinity  with the **Callback map** approach. 
of course, this is a drawback because we can not scale horizontally.  we are in the very early stage of the project so, we can wait for some weeks for this feature.

do you have a plan to implement this feature in c# since the feature I can see was merged in Zeebe?

thanks a lot

**Comment by jwulf** [comment]
We have this now in 0.22, can we get support for `CreateWorkflowInstanceWithResult` in the C# client?

**Comment by Zelldon** [comment]
I'm on it
