### ISSUE TITLE
Depend on Microsoft.Extensions.Logging.Abstractions not NLog

### ISSUE THREAD

**Issue by bobcat1506** [zeebe-io/zeebe-client-csharp#35]
**Describe the bug**
Your library should depend on Microsoft.Extensions.Logging.Abstractions not NLog.  

**To Reproduce**

**Expected behavior**
Your library should depend on Microsoft.Extensions.Logging.Abstractions not NLog.  https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/

**Additional context**
Systems should be free to choose their own logging implementation.

**Comment by Zelldon** [comment]
Thanks for bringing this up. I totally agree and migrated to [LibLog](https://github.com/damianh/LibLog)

**Comment by bobcat1506** [comment]
Christopher, Now your library has a dependency on LibLog, which consuming apps may or may not want to take on.  You really have traded one library for another.  In contrast, if you used the Microsoft.Extensions.Logging.Abstractions most logging libraries have implementations for this. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0 “.NET Core supports a logging API that works with a variety of built-in and third-party logging providers. This article shows how to use the logging API with built-in providers.” https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-2https://github.com/NLog/NLog/wiki/Getting-started-with-.NET-Core-2---Console-application The industry is going this direction and you really should consider porting to the Microsoft abstractions libraries as suggested.  For us to use this library we’d have to create a copy and remove the anything other than a reference to Microsoft.Extensions.Logging.Absractions.  You should also support constructor injection as most everyone nowadays is using DI as well. I’m not sure I can participate in an “official” capacity, but I’d be willing to assist in making the changes.  My company blocks access to GitHub so I’d need to do it on my personal time.  Let me know if I can help.  Thanks. Eric ZwiebelSenior ArchitectPNC Bank Sent from Mail for Windows 10 From: Christopher ZellSent: Wednesday, October 9, 2019 2:33 PMTo: zeebe-io/zeebe-client-csharpCc: bobcat1506; AuthorSubject: Re: [zeebe-io/zeebe-client-csharp] Depend on Microsoft.Extensions.Logging.Abstractions not NLog (#35) Thanks for bringing this up. I totally agree and migrated to LibLog—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Zelldon** [comment]
Not exactly it is more a logging facade. Even if you use the extension you have to build something similar. This "dependency" is also only visible for the assembly which contains the LibLog.cs.This means for the lib users it is transparent and they can just use the loging lib they want and this will automatically be detected.

Take a look here

https://github.com/damianh/LibLog/wiki
https://lunarfrog.com/blog/net-open-source-netstandard-logging-using-liblog

**Comment by bobcat1506** [comment]
Yes, it's an abstraction which is the point.  You don't have to build your own implementation, you register an ILogger implementation in your DI container and your DI container injects it as needed via constructor injection.  We have done this in our own "Foundations" libraries which are leveraged in many apps and it works out great.  Some systems are using NLog, some are using SeriLog, and some have rolled their own custom implementations.  Consider this:

LibLog has less than 1M downloads on NuGet.
Common.Logging has almost 11M downloads on NuGet.
Microsoft.Extensions.Logging.Abstractions has 165M downloads on NuGet.

The downloads speak for themselves.  In the world of logging abstractions Microsoft's is king.  That's the way we are heading and everyone else in the industry that I've talked to is doing the same.

Some argue that libraries shouldn't implement any logging whatsoever (because of this issue) and leave that up to the application.  With as minimal as the logging is would you consider eliminating the logging all together?

**Comment by Zelldon** [comment]
It seems for me are very controversy and high discussed topic in the .net world. This is weird to me, coming from Java where one facade (slf4j) is used everywhere.

Not sure whether download count is really a good marker. New software have to start somewhere and normal at zero. It seems some other OS Project thinking of migrating to LibLog instead of the extensions and they have also lot of discussions about that. I had just spent my morning with reading lot of blogs and github issues :see_no_evil: 

> Some argue that libraries shouldn't implement any logging whatsoever (because of this issue) and > leave that up to the application. With as minimal as the logging is would you consider eliminating > the logging all together?

In the earlier state of this lib I had no logging, but I thought it is quite useful to see what it actually happening. For example for auto completion or when a job handler throws an exception that the job is failed etc. Do you disagree?

Do you see any real problems now, when the client uses LibLog instead directly the extensions?
Both should solve this issue, which was direct dependency to a logging library.

**Comment by bobcat1506** [comment]
Small apps are relatively simple, but large enterprise systems are either being written as micro services, are monoliths, or are a mixture in between.  Enterprise systems have a much higher level of complexity and many reference as many as 50+ NuGet packages.  Could you imagine if each NuGet package referenced a different logging implementation/abstraction?  That would exponentially complicate things.  Not to mention, many corporations (mine included) regulate the use of OS software and new libraries are difficult to get approved.  If you're going to include logging you should pick the most common abstraction or do it as a separate extension library to your core component to maximize flexibility and adoption.  

Like I said, the ONLY way we'd be able to use this library would be to fork it and eliminate the LibLog dependencies.  By forking it we may not even be able to get it approved.  I would imagine that most (80% or more) people are in the same boat as we are.

And like I said if we forked it we would make the ILogger a parameter on the constructor and register NLog and the relevant Zeebe services/classes in our Dependency Injection container and use DI to activate the Zeebe client and manage its lifetime.  We would depend on Microsoft.Extensions.DependencyInjection.Abstractions and provide extension method(s) to wire up DI and we'd call those methods in our startup sequence when we configure our DI container.

I also appreciate the discussion.  I hope I've provided some valuable insight.  Would it be beneficial if I forked the project and made the changes I've described?

**Comment by Zelldon** [comment]
Hey @bobcat1506 thank you very much for your time and for the insights, it helps me a lot to understand the issue/situation you have. 

>  Would it be beneficial if I forked the project and made the changes I've described?

This would be **awesome**, if you could create an PR with the changes which you want to make and we can discuss the parts there. Does it make sense to have the `ILogger` as parameter or more the `ILoggerFactory`? Such that the different classes can then create there own logger object?

**Comment by Zelldon** [comment]
closed by https://github.com/zeebe-io/zeebe-client-csharp/commit/14ddfac4334e52d4e51809052c1a21bd269d4e64
