### ISSUE TITLE
JobWorker.FailActivatedJob does not await NewFailCommand

### ISSUE THREAD

**Issue by bobcat1506** [zeebe-io/zeebe-client-csharp#41]
**Describe the bug**
JobWorker.FailActivatedJob does not await NewFailCommand

https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/because-this-call-is-not-awaited-the-current-method-continues-to-run

**Comment by Zelldon** [comment]
Why do you think we need to wait here? What would like to do with the result? Or is it more for repeat the request if it fails?

**Comment by bobcat1506** [comment]
"...because no Await operator is applied, the program continues without waiting for the task to complete. In most cases, that behavior isn't expected. Usually other aspects of the calling method depend on the results of the call or, minimally, the called method is expected to complete before you return from the method that contains the call.

An equally important issue is what happens with exceptions that are raised in the called async method. An exception that’s raised in a method that returns a Task or Task<TResult> is stored in the returned task. If you don't await the task or explicitly check for exceptions, the exception is lost. If you await the task, its exception is rethrown.

**As a best practice, you should always await the call**."

Also, firing and forgetting requests to the server can result in a high number of concurrent calls to the server and can easily overwhelm it.

Just await the call so the code does not overwhelm the server and you can log/handle exceptions.
