### ISSUE TITLE
I can use the client to automatically handle gRPC 14 and 8 transient failures

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-client-csharp#69]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to write backpressure and network failure handling manually.

**Describe the solution you'd like**
Configurable retries with something like https://github.com/App-vNext/Polly baked in.

**Comment by Zelldon** [comment]
Thanks for raising this issue. How you do it in the nodejs client? Do you think it make sense to make this behavior configurable? Not sure whether it make sense to retry endless or only a specific amount of times. 

Should it be a opt-in thing or default behavoir.

**Comment by berndruecker** [comment]
Great discussion folks. With the risk of killing the enthusiasm I think we should briefly discuss 

- What's a good behavior of the client?
- What shall clients do and behave in that sense?
- How can we describe that properly for users to understand?

And then we should implement the exact same behavior in the different language clients (if that make sense). Or WDYT?

I think the topic is really important, but also not an easy pick. Especially as the question raised are important: What is the best practice? Does retrying is a great idea if the broker is already overloaded? So personally I am not yet familiar with the proper back pressure best practices - so I feel that we should figure that out first.

**Comment by Zelldon** [comment]
> What shall clients do and behave in that sense?

Good question. With the current solution the user is forced to do the handling, but we can also say that this is his own freedom. Might be that he don't want to retry, who knows? :man_shrugging: 

> And then we should implement the exact same behavior in the different language clients (if that make sense). Or WDYT?

Makes totally sense from my side. I thought the same, we should try to be consistent in the different clients.

> So personally I am not yet familiar with the proper back pressure best practices - so I feel that we should figure that out first. 

Yes totally agree. I'm also not sure if this get better if we just dump retry endless, without any logic behind that. But it seems the lib Josh shared seems to implement already some strategies.

**Comment by berndruecker** [comment]
Would be nice to learn if Polly can something specifically, I "only" know it for circuit breaking and retrying - but the latter typically used for leaky networks, where a retry is a good strategy. But I think this does not translate one-to-one to back-pressure.

A "in the middle" strategy could be a blog post about back pressure handling strategies, see how customer react and what they implement - and decide on client features later when we better understand what make sense?

**Comment by jwulf** [comment]
http://zeebe.joshwulf.com/grpc/grpc-config/

Based on my experience using it.

**Comment by Zelldon** [comment]
What do you guys think about a new send method called `SendWithRetry` as addition to the normal send method? So the user has the choice about the auto. retry handling.

**Comment by Zelldon** [comment]
Created as first step https://github.com/zeebe-io/zeebe-client-csharp/pull/172 and sub issues.
