### ISSUE TITLE
ZeebeClient with aspnet core project

### ISSUE THREAD

**Issue by LZorglub** [zeebe-io/zeebe-client-csharp#76]
Using references on Microsoft DependencyInjection version 3.1.0 prevents me from using the zeebe-client with an aspnet core 2.1 project.

    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.0" />

Normally keeping a reference on 2.1.1 version allow us to use it in aspnet core 2.1 and 3.1

**Comment by Zelldon** [comment]
Thanks for reporting this. I created a new release, where I bumped that version 
https://github.com/zeebe-io/zeebe-client-csharp/releases/tag/0.14.0
