### ISSUE TITLE
Nuget package references wrong URL site

### ISSUE THREAD

**Issue by LZorglub** [zeebe-io/zeebe-client-csharp#85]
Your nuget package reference the https://github.com/zeebe-io/zeebe-csharp-client instead of https://github.com/zeebe-io/zeebe-client-csharp

Last two words inverted.

**Comment by Zelldon** [comment]
Thanks for reporting. I already fixed that with https://github.com/zeebe-io/zeebe-client-csharp/commit/369e95b00e8c9bb15197c606bd25254a7073d242
