### ISSUE TITLE
Stop logging when no active job requested

### ISSUE THREAD

**Issue by LZorglub** [zeebe-io/zeebe-client-csharp#86]
When no jobs are pending we trace :

`
fail: Zeebe.Client.Impl.Worker.JobWorker[0]
      Unexpected RpcException on polling new jobs.
Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")
`

Can becomes difficult to read log file after a while. Can be worth it to not log this ?

**Comment by Zelldon** [comment]
Hey @LZorglub,

thanks for reporting this. 

So you would suggest to remove this? Could also be a different error, which is maybe interesting for you? Might be enough to change the log level or add a back off, like log every 100x. What do you think?

**Comment by LZorglub** [comment]
Would be nice to only filter log when no jobs are pending. When the server is not reachable the error is 
`
fail: Zeebe.Client.Impl.Worker.JobWorker[0]
      Unexpected RpcException on polling new jobs.
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")
`

StatusCode = Unavailable must be logged as Error and it's the actual behavior that i expect.

If StatusCode=DeadlineExceeded happend only when no jobs are return (seems related to timeout) so yes something like logging only every 100x seems good compromise.

**Comment by Zelldon** [comment]
Yes, this makes sense to me thanks

**Comment by bulldetektor** [comment]
Logging every nth exception will be quite complex when taking into account threading issues and other failure situations. My suggestion (see PR above) is to log DeadlineExceeded and Cancelled with log level `Debug` instead (cancelled because we don't want any error logged when the application is shutting down)

**Comment by LZorglub** [comment]
Yes make sense.
